name: Docker Script de Bienvenida

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Construir imagen Docker
      run: |
        docker build -t script-bienvenida .
    
    - name: Ejecutar contenedor
      run: |
        docker run --rm \
          -e USUARIO_NOMBRE="Gonzalo" \
          -e AMBIENTE="CI/CD" \
          script-bienvenida
    
    - name: Mostrar información del contenedor
      run: |
        echo "Contenedor ejecutado exitosamente!"
        docker images | grep script-bienvenida
